apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-app
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
        - image: avetall87/library-app:latest
          imagePullPolicy: Always
          name: library-app
          ports:
            - containerPort: 8080