spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    ROOT: INFO

rest:
  reddit:
    timeout:
      millis:
        connection: 60000
        read: 60000

integration:
  bus:
    queue:
      size: 10

reddit:
  filter:
    token: TEST-TOKEN