version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres:11.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    volumes:
      - ./db/storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  postgres_mail:
    container_name: postgres_container_mail
    image: postgres:11.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    volumes:
      - ./db/mail/storage:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./index/storage:/usr/share/elasticsearch/data
    ports:
      - 9200:9200