spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgrespass
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: login
    password: password
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

logging:
  level:
    ROOT: INFO

rest:
  timeout:
    millis:
      connection: 60000
      read: 60000

index:
  service:
    url: http://localhost:8082

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    diskspace:
      enabled: true
  endpoint:
    health:
      show-details: always