version: '3'
services:
  library-app-web:
    depends_on:
      - library-app
    ports:
      - '80:80'
    image: avetall87/library-app-web:latest
  library-app:
    depends_on:
      - database # старт после старта контейнера mongo
    image: 'library-app:latest'
    container_name: 'library-app'
    ports:
    - '8080:8080'
  database:
    image: 'mongo'
    container_name: 'study-mongo-db'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=library-db
      - MONGO_INITDB_ROOT_USERNAME=library
      - MONGO_INITDB_ROOT_PASSWORD=library
    volumes:
      - ./data/db:/data/db
      - ./init-tmongo.js:/data/init
    ports:
      - '27017:27017'